name: Production
on:
  push:
    branches: ["master"]

jobs:
  checking-project:
    runs-on: ubuntu-latest

    steps:
      - name: "Get project ${{ github.event.repository.name }}"
        uses: actions/checkout@v3

      - name: Uses Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Install Dependencies"
        run: yarn

      - name: "Test features"
        run: yarn test:verbose

      - name: "Build Project"
        run: yarn build

  build:
    needs: checking-project
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        env:
          PROJECT_NAME: ${{ github.event.repository.name }}
          PROJECT_SSH_CLONE: git@github.com:Icaro-Davi/${{ github.event.repository.name }}.git
          PROJECT_ENVS: ${{ secrets.PROJECT_ENVS }}
        with:
          host: ${{ secrets.DOMAIN }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHPRIVATEKEY }}
          script: sudo bash ~/PROJECTS/BASH/install-dependencies.bash && bash ~/PROJECTS/BASH/get-project-from-git.bash
